apiVersion: v1
kind: Service
metadata:
  name: image-server
  namespace: "{{ .Values.global.xraylab.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "15"
    app.kubernetes.io/managed-by: "Helm"
    meta.helm.sh/release-name: "image-server"
    meta.helm.sh/release-namespace: "default"
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    name: image-server
