kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: image-server
  namespace: "{{ .Values.global.xraylab.namespace }}"
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "10"
    app.kubernetes.io/managed-by: "Helm"
    meta.helm.sh/release-name: "image-server"
    meta.helm.sh/release-namespace: "default"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: image-server
    spec:
      containers:
        - name: image-server
          image: "docker.io/aiannaccaro/gramine:python3-makev12"
          env:
            - name: database_user
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database-user
            - name: database_password
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database-password
            - name: database_host
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database-host
            - name: database_db
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database-db
            - name: service_point
              valueFrom:
                configMapKeyRef:
                  name: service-point
                  key: url-external
            - name: bucket_base_name
              valueFrom:
                configMapKeyRef:
                  name: buckets-config
                  key: bucket-base-name
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 500M
            requests:
              cpu: 400m
              memory: 100M
          volumeMounts:
            - name: dev-sgx
              mountPath: /dev/sgx_enclave
          securityContext:
            privileged: true
            capabilities:
              add:
                - IPC_LOCK
          imagePullPolicy: IfNotPresent
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/sgx_enclave
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
