apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: image-server
  namespace: "{{ .Values.global.xraylab.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    app.kubernetes.io/managed-by: "Helm"
    meta.helm.sh/release-name: "image-server"
    meta.helm.sh/release-namespace: "default"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: {{ .Values.imageStream.tags.name }}
      from:
        kind: DockerImage
        name: {{ .Values.imageStream.from.name }}
      importPolicy: {}
      referencePolicy:
        type: Source
