apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-1"
  name: job-odf-cephobjectstore-complete
  namespace: {{ .Values.global.xraylab.namespace }}
spec:
  template:
    spec:
      containers: 
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          oc wait --for=jsonpath='{.status.phase}'=Connected cephobjectstore/ocs-storagecluster-cephobjectstore -n openshift-storage --timeout=900s
        name: wait-odf-cephobjectstore-complete
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: {{ .Values.global.xraylab.namespace }}-sa
      serviceAccountName: {{ .Values.global.xraylab.namespace }}-sa
      terminationGracePeriodSeconds: 60
