apiVersion: v1
kind: ConfigMap
metadata:
  name: buckets-config
  namespace: "{{ .Values.global.xraylab.namespace }}"
data:
  bucket-source: "{{ .Values.images.bucketSource }}"
  bucket-base-name: "{{ .Values.images.bucketBaseName }}"
