clusterGroup:
  name: datacenter
  isHubCluster: true

  namespaces:
  - open-cluster-management
  - openshift-serverless
  - opendatahub
  - openshift-storage
  - xraylab-1
  - knative-serving
  - staging
<<<<<<< HEAD
=======
<<<<<<< HEAD
  - vault
  - golang-external-secrets
=======
>>>>>>> e93575d (Drop vault usage from medical-diagnosis)
>>>>>>> day0hero-jrickard-cleanupdate
  - medical-diagnosis-datacenter

  operatorgroupExcludes:
    - operatorhub
    - knative-kafka

  subscriptions:
  - name: amq-streams
    namespace: xraylab-1 
    channel: stable
    csv: amqstreams.v1.7.1

  - name: grafana-operator
    namespace: xraylab-1 
    channel: v4
    source: community-operators
    csv: grafana-operator.v3.10.3

  - name: odf-operator
    namespace: openshift-storage
    channel: stable-4.10
    csv: ocs-operator.v4.10.2

  - name: serverless-operator
    channel: stable
    csv: serverless-operator.v1.7.2

  - name: opendatahub-operator
    source: community-operators
    csv: opendatahub-operator.v1.1.0


  projects:
  - datacenter
 
  applications:
<<<<<<< HEAD
    acm:
      name: acm
      namespace: open-cluster-management
      project: datacenter
      path: common/acm

    odh:
      name: odh
      namespace: opendatahub
      project: datacenter
      path: charts/datacenter/opendatahub

    cephobjectstore:
      name: cephobjectstore
      namespace: openshift-storage
      project: datacenter
      path: charts/datacenter/cephobjectstore

    knative:
      name: knative
      namespace: xraylab-1
      project: datacenter
      path: charts/datacenter/xraylab/knative

    demo:
      name: demo
      namespace: xraylab-1
      project: datacenter
      path: charts/datacenter/xraylab/demo

    user:
      name: user
      namespace: xraylab-1
      project: datacenter
      path: charts/datacenter/xraylab/user

    kafka:
      name: kafka
      namespace: xraylab-1
      project: datacenter
      path: charts/datacenter/xraylab/kafka

    kafkasource:
      name: kafkasource
      namespace: xraylab-1
      project: datacenter
      path: charts/datacenter/xraylab/kafkasource

=======
  - name: vault
    namespace: vault
    project: datacenter
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: v0.20.0
    overrides:
    - name: global.openshift
      value: "true"
    - name: injector.enabled
      value: "false"
    - name: ui.enabled
      value: "true"
    - name: ui.serviceType
      value: LoadBalancer
    - name: server.route.enabled
      value: "true"
    - name: server.route.host
      value: null
    - name: server.route.tls.termination
      value: edge
    - name: server.image.repository
      value: "registry.connect.redhat.com/hashicorp/vault"
    - name: server.image.tag
      value: "1.10.3-ubi"

  - name: golang-external-secrets
    namespace: golang-external-secrets
    project: datacenter
    path: common/golang-external-secrets

  - name: odh
    namespace: opendatahub
    project: datacenter
    path: charts/datacenter/openDataHub

  - name: odf
    namespace: openshift-storage
    project: datacenter
    path: charts/datacenter/openshiftDataFoundations

  - name: serverless
    namespace: xraylab-1
    project: datacenter
    path: charts/datacenter/openshiftServerless
  
  - name: kafka
    namespace: xraylab-1
    project: datacenter
    path: charts/datacenter/kafka
  
  - name: kafdrop
    namespace: xraylab-1
    project: datacenter
    path: charts/datacenter/kafdrop
  
  - name: xraylab-service-account
    namespace: xraylab-1
    project: datacenter
    path: charts/datacenter/medical-diagnosis/service-account

  - name: xraylab-init
    namespace: xraylab-1
    project: datacenter
    path: charts/datacenter/medical-diagnosis/xray-init

  - name: xraylab-database
    namespace: xraylab-1
    project: datacenter
    path: charts/datacenter/medical-diagnosis/database
  
  - name: xraylab-grafana-dashboards
    namespace: xraylab-1
    project: datacenter
    path: charts/datacenter/medical-diagnosis/grafana

  - name: xraylab-image-server
    namespace: xraylab-1
    project: datacenter
    path: charts/datacenter/medical-diagnosis/image-server
    ignoreDifferences:
    - group: apps.openshift.io
      kind: DeploymentConfig
      jqPathExpressions:
      - '.spec.template.spec.containers[].image'

<<<<<<< HEAD
  - name: xraylab-image-generator
    namespace: xraylab-1
    project: datacenter
    path: charts/datacenter/medical-diagnosis/image-generator
    ignoreDifferences:
    - group: apps.openshift.io
      kind: DeploymentConfig
      jqPathExpressions:
      - '.spec.template.spec.containers[].image'
=======
>>>>>>> day0hero-jrickard-cleanupdate
    grafana:
      name:  grafana
      namespace: xraylab-1
      project: datacenter
      path: charts/datacenter/xraylab/grafana

    imageserver:
      name: imageserver
      namespace: xraylab-1
      project: datacenter
      path: charts/datacenter/xraylab/image-server

    imagegenerator:
      name: imagegenerator
      namespace: xraylab-1
      project: datacenter
      path: charts/datacenter/xraylab/image-generator

    xraydb:
      name: xraydb
      namespace: xraylab-1
      project: datacenter
      path: charts/datacenter/xraylab/xraydb
<<<<<<< HEAD
=======
>>>>>>> e93575d (Drop vault usage from medical-diagnosis)
>>>>>>> day0hero-jrickard-cleanupdate

#  To have apps in multiple flavors, use namespaces and use helm overrides as appropriate
#
#    pipelines:
#      name: pipelines
#      namespace: production
#      project: datacenter
#      path: applications/pipeline
#      repoURL: https://github.com/you/applications.git
#      targetRevision: stable
#      overrides:
#      - name: myparam
#        value: myparam
#
#    pipelines_staging:
#    - name: pipelines
#      namespace: staging
#      project: datacenter
#      path: applications/pipeline
#      repoURL: https://github.com/you/applications.git
#      targetRevision: main
#
#   Additional applications
#   Be sure to include additional resources your apps will require
#   +X machines
#   +Y RAM
#   +Z CPU
#    vendor-app:
#      name: vendor-app
#      namespace: default
#      project: vendor
#      path: path/to/myapp
#      repoURL: https://github.com/vendor/applications.git
#      targetRevision: main

#  managedSites:
#    factory:
#      name: factory
#      # repoURL: https://github.com/dagger-refuse-cool/manuela-factory.git
#      targetRevision: main
#      path: applications/factory
#      helmOverrides:
#      - name: site.isHubCluster
#        value: false
#      clusterSelector:
#        matchExpressions:
#        - key: vendor
#          operator: In
#          values:
#            - OpenShift

  managedSites:
    edge:
      name: edge
      # repoURL: https://github.com/dagger-refuse-cool/manuela-factory.git
      targetRevision: main
      helmOverrides:
      - name: site.isHubCluster
        value: "false"
      clusterSelector:
        matchExpressions:
        - key: vendor
          operator: In
          values:
            - OpenShift
