global:
  pattern: xray
  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  # XRay configuration for service-point config map
  # Found in charts/datacenter/xraylab/templates
  #   datacenter:
  #     cloudProvider: <aws,azure,gcp>
  #     storageClassName: <gp2>
  #     region: <us-east-1>
  #     clustername: <cluster-name>
  #     domain: <domain>

  datacenter:
    cloudProvider: aws
    storageClassName: gp2
    region: us-east-1
    clustername: jrickard-xray411
    domain: blueprints.rhecoeng.com

  xraylab:
    namespace: "xraylab-1"

    s3:
      # Values for S3 bucket access
      # bucketSource: "provide s3 bucket name where images are stored"
      bucketSource: validated-patterns.xray-source
      # Bucket base name used for image-generator and image-server applications. 
      bucketBaseName: "xray-source"

main:
  clusterGroupName: datacenter
