global:
  pattern: xray
  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  # XRay configuration for service-point config map
  # Found in charts/datacenter/xraylab/templates
  #   datacenter:
  #     cloudProvider: <aws,azure,gcp>
  #     storageClassName: <gp2>
  #     region: <us-east-1>
  #     clustername: <cluster-name>
  #     domain: <domain>

  datacenter:
    cloudProvider: PROVIDE_CLOUDPROVIDER
    storageClassName: PROVIDE_STORAGECLASS_NAME
    region: PROVIDE_REGION
    clustername: PROVIDE_CLUSTERNAME
    domain: PROVIDE_DOMAIN

  xraylab:
    namespace: "xraylab-1"

    s3:
      # Values for S3 bucket access
      # bucketSource: "provide s3 bucket name where images are stored"
      bucketSource: PROVIDE_BUCKETSOURCE
      # Bucket base name used for image-generator and image-server applications. 
      bucketBaseName: "xray-source"

main:
  clusterGroupName: datacenter
