---
version: "2.0"
secrets:
  # NEVER COMMIT THESE VALUES TO GIT
  
  # Database login credentials and configuration
  - name: xraylab
    fields:
    - name: database-user
      value: xraylab
    - name: database-host
      value: xraylabdb
    - name: database-db
      value: xraylabdb
    - name: database-master-user
      value: xraylab
    - name: database-password
      value: demo1
      onMissingValue: generate
      vaultPolicy: validatedPatternDefaultPolicy
    - name: database-root-password
      value: demo1
      onMissingValue: generate
      vaultPolicy: validatedPatternDefaultPolicy
    - name: database-master-password
      value: demo1
      onMissingValue: generate
      vaultPolicy: validatedPatternDefaultPolicy
  
  # Grafana Dashboard admin user/password
  - name: xraylab
    fields:
    - name: GF_SECURITY_ADMIN_USER
      value: root
    - name: GF_SECURITY_ADMIN_PASSWORD
      value: demo1
      onMissingValue: generate
      vaultPolicy: validatedPatternDefaultPolicy
