---
secrets:
  # NEVER COMMIT THESE VALUES TO GIT
  
  # Database login credentials and configuration
  xraylab:
    database-user: xraylab
    database-password: demo1
    database-root-password: demo1
    database-host: xraylabdb
    database-db: xraylabdb
    database-master-user: xraylab
    database-master-password: demo1
  
  # Grafana Dashboard admin user/password
  grafana:
    GF_SECURITY_ADMIN_USER: root
    GF_SECURITY_ADMIN_PASSWORD: demo1
    GF_DATASRC_USER: xraylab
    GF_DATASRC_PASSWORD: demo1
    GF_DATASRC_DB: xraylabdb
    GF_DATASRC_URL: xraylabdb
