clusterGroup:
  name: datacenter
  isHubCluster: true

  namespaces:
  - open-cluster-management
  - openshift-serverless
  - opendatahub
  - openshift-storage
  - xraylab-1
  - knative-serving
  - staging
  - vault
  - medical-diagnosis-datacenter

  operatorgroupExcludes:
    - operatorhub
    - knative-kafka

  subscriptions:
  - name: advanced-cluster-management
    namespace: open-cluster-management
    channel: release-2.3
    csv: advanced-cluster-management.v2.3.2

  - name: amq-streams
    namespace: xraylab-1 
    channel: stable
    csv: amqstreams.v1.7.1

  - name: grafana-operator
    namespace: xraylab-1 
    channel: v4
    source: community-operators
    csv: grafana-operator.v3.10.3

  - name: odf-operator
    namespace: openshift-storage
    channel: stable-4.10
    csv: ocs-operator.v4.10.2

  - name: serverless-operator
    channel: stable
    csv: serverless-operator.v1.7.2

  - name: opendatahub-operator
    source: community-operators
    csv: opendatahub-operator.v1.1.0


  projects:
  - datacenter
 
  applications:
  - name: acm
    namespace: open-cluster-management
    project: datacenter
    path: common/acm

  - name: odh
    namespace: opendatahub
    project: datacenter
    path: charts/datacenter/openDataHub

  - name: odf
    namespace: openshift-storage
    project: datacenter
    path: charts/datacenter/openshiftDataFoundations

  - name: serverless
    namespace: xraylab-1
    project: datacenter
    path: charts/datacenter/openshiftServerless
  
  - name: kafka
    namespace: xraylab-1
    project: datacenter
    path: charts/datacenter/kafka
  
  - name: kafdrop
    namespace: xraylab-1
    project: datacenter
    path: charts/datacenter/kafdrop
  
  - name: service-account
    namespace: xraylab-1
    project: datacenter
    path: charts/datacenter/medical-diagnosis/service-account

  - name: object-store-user
    namespace: xraylab-1
    project: datacenter
    path: charts/datacenter/medical-diagnosis/object-store-user

  - name: xraylab-database
    namespace: xraylab-1
    project: datacenter
    path: charts/datacenter/medical-diagnosis/database
  
  - name: xraylab-grafana-dashboards
    namespace: xraylab-1
    project: datacenter
    path: charts/datacenter/medical-diagnosis/grafana

  - name: xraylab-image-server
    namespace: xraylab-1
    project: datacenter
    path: charts/datacenter/medical-diagnosis/image-server

  - name: xraylab-risk-assessment
    namespace: xraylab-1
    project: datacenter
    path: charts/datacenter/medical-diagnosis/risk-assessment

  - name: xraylab-image-generator
    namespace: xraylab-1
    project: datacenter
    path: charts/datacenter/medical-diagnosis/image-generator

#
#  To have apps in multiple flavors, use namespaces and use helm overrides as appropriate
#
#  - name: pipelines
#    namespace: production
#    project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: stable
#    overrides:
#    - name: myparam
#      value: myparam 
#  
#  - name: pipelines
#    namespace: staging
#    project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: main
#  
#   Additional applications
#   Be sure to include additional resources your apps will require
#   +X machines
#   +Y RAM
#   +Z CPU
#  - name: vendor-app
#    namespace: default
#    project: vendor
#    path: path/to/myapp
#    repoURL: https://github.com/vendor/applications.git
#    targetRevision: main

  managedSites:
  - name: edge
    # repoURL: https://github.com/dagger-refuse-cool/manuela-factory.git
    targetRevision: main
    helmOverrides:
    - name: site.isHubCluster
      value: "false"
    clusterSelector:
      matchExpressions:
      - key: vendor
        operator: In
        values:
          - OpenShift

