global:
  pattern: xray

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  datacenter:
    cloudProvider: azure
    storageClassName: azurefile-csi
    region: northeurope
    clustername: edgemedical
    domain: acicrome.local

  xraylab:
    namespace: "xraylab-1"

    s3:
      bucketSource: https://xrayazurebucket.blob.core.windows.net/edgemedical/
      bucketBaseName: "xray-source"

main:
  clusterGroupName: hub

#export AWS_ACCESS_KEY_ID=AKXXXXXXXXXXXXX
#export AWS_SECRET_ACCESS_KEY=gkXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX