{{- range .Values.rbac.clusterRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - apiGroups:
      - {{ .apiGroups }}
    resources:
      - {{ .resources }}
    verbs: [{{ join ", " .verbs }}]
{{- end }}