apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbac.clusterRole.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - apiGroups:
      - {{ .Values.rbac.clusterRole.apiGroups }}
    resources:
      - {{ .Values.rbac.clusterRole.resources }}
    verbs: [{{ join ", " .Values.rbac.clusterRole.verbs }}]