apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: "{{ .Values.global.xraylab.namespace }}"  
stringData:
  database-user: "{{ .Values.secrets.xraylab.database_user }}"
  database-password: "{{ .Values.secrets.xraylab.database_password }}"
  database-root-password: "{{ .Values.secrets.xraylab.database_root_password }}"
  database-host: "{{ .Values.secrets.xraylab.database_db }}"
  database-db: "{{ .Values.secrets.xraylab.database_host }}"
  database-master-password: "{{ .Values.secrets.xraylab.database_master_password }}"
  database-master-user: "{{ .Values.secrets.xraylab.database_master_password }}"
