apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: image-init
spec:
  lookupPolicy:
    local: true
  tags:
    - name: {{ .Values.imageStream.tags.name }}
      from:
        kind: DockerImage
        name: {{ .Values.imageStream.from.name }}
      importPolicy: {}
      referencePolicy:
        type: Source