global:
  xraylab:
    namespace: xraylab-1
kafkaSource:
  bootstrapserver: "xray-cluster-kafka-bootstrap.xraylab-1.svc:9092"
  name: "xray-images"
  consumerGroup: "risk-assessment"

createRole: false

job:
  image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest

rbac:
  roles:
    - name: view-deploymentConfigs
      createRole: true
      apiGroups:
        - 'apps.openshift.io' 
      scope:
        cluster: false
        namespace: xraylab-1
      resources: 
        - deploymentconfigs
      verbs:
        - "get"
        - "list"
        - "watch"
  roleBindings:
    - name: view-deploymentConfigs
      createBinding: true
      scope:
        cluster: false
        namespace: xraylab-1
      subjects:
        kind: ServiceAccount
        name: ""
        namespace: xraylab-1
        apiGroup: ""
      roleRef:
        kind: Role
        name: view-deploymentConfigs
