{{- range .Values.rbac.clusterRole }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .binding }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .name }}
subjects:
  - kind: ServiceAccount
    name: {{ $.Values.global.xraylab.namespace }}-sa
    namespace: {{ $.Values.global.xraylab.namespace }}
{{- end }}