global:
  xraylab:
    namespace: xraylab-1
  datacenter:
    clustername: 

s3:
  bucketSource: 
  bucketBaseName: "xraylab-1"

#Changing to ODF vs OCS
odf:
  serviceUrl: "http://rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc.cluster.local"
  externalUrl: "https://s3-rgw-openshift-storage"
  targetBucket: com.redhat.jrickard.xray-source

job:
  image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest

objectStore:
  user:
    name: ocs-storagecluster-cephobjectstore

rbac:
  clusterRoles:
    - name: cephobjecstoreuser-reader
      apiGroups:
        - "ceph.rook.io"
      resources: 
        - cephobjectstoreuser
      verbs:
        - "get"
        - "list"
        - "watch"
  roleBindings:
    - name: cephobjecstoreuser-reader
      scope:
        cluster: true
        namespace: openshift-storage
      subjects:
        kind: ServiceAccount
        name: ""
        namespace: ""
        apiGroup: ""
      roleRef:
        kind: ClusterRole
        name: cephobjecstoreuser-reader