global:
  xraylab:
    namespace: xraylab-1
  datacenter:
    clustername: gitops
  s3:
    bucketBaseName: xray-source

#xraylab:
  #Commented out by jrickard - changed variable inside of template to use global value for clustername and domain
  #imageServer: https://image-server-xraylab-1.apps.jrickard-med-diag.blueprints.rhecoeng.com
#  bucketBaseName: xray-source

rbac:
  roles:
    - name: grafana-mgmt
      apiGroups:
        - "integreatly.org"
      scope:
        cluster: false
        namespace: xraylab-1
      resources: 
        - grafanadatasources
      verbs:
        - "get"
        - "list"
        - "patch"
        - "create"
        - "update"
    - name: read-namespace-secrets
      apiGroups:
        - '""'
      scope:
        cluster: false
        namespace: xraylab-1
      resources:
        - secrets
      verbs:
        - "get"
        - "list"
        - "watch"
  roleBindings:
    - name: grafana-read-secrets
      scope:
        cluster: false
        namespace: xraylab-1
      subjects:
        kind: ServiceAccount
        name: grafana-serviceaccount
        namespace: xraylab-1
        apiGroup: ""
      roleRef:
        kind: Role
        name: read-namespace-secrets
    - name: grafana-mgmt
      scope:
        cluster: false
        namespace: xraylab-1
      subjects:
        kind: ServiceAccount
        name: grafana-serviceaccount
        namespace: xraylab-1
        apiGroup: ""
      roleRef:
        kind: Role
        name: grafana-mgmt      
    - name: cluster-monitoring-view
      scope:
        cluster: true
        namespace: ""
      subjects:
        kind: ServiceAccount
        name: grafana-serviceaccount
        namespace: xraylab-1
        apiGroup: ""
      roleRef:
        kind: ClusterRole
        name: cluster-monitoring-view
