apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "15"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  name: job-wait-for-object-user-creation
  namespace: {{ .Values.global.xraylab.namespace }}
spec:
  template:
    spec:
      containers: 
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          oc wait --for=jsonpath='{.status.phase}'=Ready cephobjectstoreuser/xraylab-1 -n openshift-storage --timeout=300s
        name: wait-for-object-user-creation
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: {{ .Values.global.xraylab.namespace }}-sa
      serviceAccountName: {{ .Values.global.xraylab.namespace }}-sa
      terminationGracePeriodSeconds: 60
