{{- range $key, $value := .Values.rbac.roleBindings }}
apiVersion: rbac.authorization.k8s.io/v1
{{- if eq $value.scope.cluster false }}
kind: RoleBinding
{{- else }}
kind: ClusterRoleBinding
{{- end }}
metadata:
  name: {{ .name }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-15"
{{- if eq $value.scope.cluster false }}
  namespace: {{ $value.scope.namespace }}
{{- end }}
subjects:
- kind: {{ $value.subjects.kind }}
  name: {{ $.Values.global.xraylab.namespace }}-sa
  namespace: {{ $value.scope.namespace | default $.Values.global.xraylab.namespace }}
  apiGroup: ""
roleRef:
  kind: {{ $value.roleRef.kind }}
  name: {{ $value.roleRef.name }}
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}