{{- if eq createRole }}
---
{{- range $key, $value := .Values.rbac.clusterRoles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .name }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "1"
rules:
  - apiGroups:
{{- range $value.apiGroups }}
      - {{ . }}
{{- end }}
    resources:
{{- range $value.resources }}
      - {{ . }}
{{- end }}
    verbs: 
{{- range $value.verbs }}
      - {{ . }}
{{- end }}
{{- end }}
{{- end }}