{{- if .Values.database.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: "{{ .Values.global.xraylab.namespace }}"  
stringData:
  database-user: "{{ .Values.database.user }}"
  database-password: "{{ .Values.database.user }}"
  database-root-password: "{{ .Values.database.user }}"
  database-host: "{{ .Values.database.host }}"
  database-db: "{{ .Values.database.name }}"
  database-master-password: "{{ .Values.database.master_user }}"
  database-master-user: "{{ .Values.database.master_user }}"
{{- end }}