---
apiVersion: "external-secrets.io/v1alpha1"
kind: ExternalSecret
metadata:
  name: xraydb-external-secret
  namespace: {{ .Values.global.xraylab.namespace }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: db-secret
    template:
      type: Opaque
  dataFrom:
    - key: {{ .Values.xraylab.key }}
