---
apiVersion: "external-secrets.io/v1alpha1"
kind: ExternalSecret
metadata:
  name: xraydb-external-secret
  namespace: {{ .Values.global.xraylab.namespace }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: config-demo-secret
    template:
      type: Opaque
  dataFrom:
    - key: {{ .Values.xraylab.key }}

------------------
stringData:
  database-user: "{{ .Values.database.user }}"
  database-password: "{{ .Values.database.user }}"
  database-root-password: "{{ .Values.database.user }}"
  database-host: "{{ .Values.database.host }}"
  database-db: "{{ .Values.database.name }}"
  database-master-password: "{{ .Values.database.master_user }}"
  database-master-user: "{{ .Values.database.master_user }}"