global:
  xraylab:
    namespace: xraylab-1
  datacenter:
    storageClassName: gp2
    region: us-east-1

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

xraylabsecret:
  key: secret/data/hub/xraylab

database:
  secret:
    create: true
  name: xraylabdb
  user: xraylab
  password: ""
  host: xraylabdb
  master_user: xraylab
  master_password: ""
  image: registry.redhat.io/rhel8/mariadb-103:latest
