global:
  xraylab:
    namespace: xraylab-1
  datacenter:
    storageClassName: gp2
    region: us-east-1

database:
  secret:
    create: true
  name: xraylabdb
  user: xraylab
  password: ""
  host: xraylabdb
  master_user: xraylab
  master_password: ""
  image: registry.redhat.io/rhel8/mariadb-103:latest

rbac:
  clusterRole:
    name: wait-for-deployment
  clusterRoleBinding:
    name: get-deployment-rolebinding

job:
  name: wait-for-deployment
  image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest