apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-5"
  name: job-imageserver-deploy-complete
  namespace: {{ .Values.global.xraylab.namespace }}
spec:
  template:
    spec:
      containers: 
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          oc wait --for=condition=available deploymentconfig/image-server -n {{ .Values.global.xraylab.namespace }} --timeout=300s
        name: wait-imageserver-deploy-complete
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: {{ .Values.global.xraylab.namespace }}-sa
      serviceAccountName: {{ .Values.global.xraylab.namespace }}-sa
      terminationGracePeriodSeconds: 60
