- hosts: localhost
  gather_facts: no

  tasks:
  - name: Wait until KNative Serving installation is complete
    k8s_info:
      api_version: operator.knative.dev/v1alpha1
      kind: KnativeServing
      name: knative-serving
      namespace: knative-serving
    register: r_kn_serving
    retries: 30
    delay: 10
    until:
    - r_kn_serving.resources[0].status.conditions[0].status is defined
    - r_kn_serving.resources[0].status.conditions[0].status == "True"
    - r_kn_serving.resources[0].status.conditions[1].status is defined
    - r_kn_serving.resources[0].status.conditions[1].status == "True"
    - r_kn_serving.resources[0].status.conditions[2].status is defined
    - r_kn_serving.resources[0].status.conditions[2].status == "True"
    - r_kn_serving.resources[0].status.conditions[3].status is defined
    - r_kn_serving.resources[0].status.conditions[3].status == "True"
  
    - name: Wait until KNative Eventing installation is complete
      k8s_info:
        api_version: operator.knative.dev/v1alpha1
        kind: KnativeEventing
        name: knative-eventing
        namespace: knative-eventing
      register: r_kn_eventing
      retries: 30
      delay: 10
      until:
      - r_kn_eventing.resources[0].status.conditions[0].status is defined
      - r_kn_eventing.resources[0].status.conditions[0].status == "True"
      - r_kn_eventing.resources[0].status.conditions[1].status is defined
      - r_kn_eventing.resources[0].status.conditions[1].status == "True"
