knative:
  operators:
    - kind: "KnativeServing"
      name: "knative-serving"
      namespace: "knative-serving"
    - kind: "KnativeEventing"
      name: "knative-eventing"
      namespace: "knative-eventing"
    - kind: "KnativeKafka"
      name: "knative-kafka"
      namespace: "knative-eventing"