---
apiVersion: "external-secrets.io/v1alpha1"
kind: ExternalSecret
metadata:
  name: grafana-creds-external-secret
  namespace: {{ .Values.global.xraylab.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: grafana-creds
    template:
      type: Opaque
  data:
  - secretKey: GF_SECURITY_ADMIN_USER
    remoteRef: 
      key: secret/hub/grafana
      property: GF_SECURITY_ADMIN_USER
  - secretKey: GF_SECURITY_ADMIN_PASSWORD
    remoteRef:
      key: secret/hub/grafana
      property: GF_SECURITY_ADMIN_PASSWORD
