apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: mysql-grafana-datasource
  namespace: {{ .Values.global.xraylab.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  datasources:
    - type: {{ .Values.dataSources.type }}
      name: {{ .Values.dataSources.name }}
      access: {{ .Values.dataSources.access }}
      url: {{ .Values.dataSources.url }}
      database: {{ .Values.dataSources.database }}
      user: {{ .Values.dataSources.user }}
      password: {{ coalesce .Values.dataSources.password .Values.dataSources.user  }}
  name: mysql-grafana-datasource.yaml
